### ISSUE TITLE
'Auto Dark Mode' proposal

### ISSUE THREAD

**Issue by iamdtms** [linuxmint/cinnamon-desktop#241]
Automatically switches between the dark and light theme would be nice. We have dark theme, we have light theme, so why do not we change Cinnamon theme this way from sunset to sunsire in a Linux environment as well. Hope it can be done easily.

**Comment by rcalixte** [comment]
This is probably best as an extension or applet if there is an interested developer who wants to create and/or maintain it. There is at least one example of each that implements similar sunrise/sunset functionality:

* Applet: [Redshift](https://cinnamon-spices.linuxmint.com/applets/view/296)
* Extension: [Cinnamon Dynamic Wallpaper](https://cinnamon-spices.linuxmint.com/extensions/view/97)

**Comment by clefebvre** [comment]
It sounds like a weird idea to me. Dark/light strikes me as a subjective preference, with some people clearly preferring one or the other.

It makes sense for a car or a smartphone to maybe do that on its own to reduce brightness when you're about to go to bed, or someone is sleeping next to you, or you're driving at night.. but for a computer it makes less sense imo.

I'm not opposed to seeing it done in Cinnamon though, but it's not something I'd work on personally.

Closing since the team is aware of the feature request.

**Comment by Starcross** [comment]
Just to add a little to the above discussion and to register my interest, I'd love to see this feature. I think there is a lot of crossover in the way laptops and tablets/phones are used. 

To me it feels more natural to have a dark theme in the evening when my environment is less brightly lit. Less glare and more relaxing.

However in the daytime I find it easier to read text with a light theme, and in particular helps combat reflections on the screen from any windows behind me.
